

KEY_EVENT(VPK_KEY_EVENT_SYS_ACC_ON,		VPK_EVENT_NOTICE,	EVENT_SYS_ACC_ON,		0x1001,	"acc on")
KEY_EVENT(VPK_KEY_EVENT_SYS_ACC_OFF,	VPK_EVENT_NOTICE,	EVENT_SYS_ACC_OFF,		0x1002,	"acc off")
KEY_EVENT(VPK_KEY_EVENT_SYS_FAST_ACC,	VPK_EVENT_NOTICE,	EVENT_SYS_FAST_ACC,		0x1003,	"fast accelerate")
KEY_EVENT(VPK_KEY_EVENT_SYS_FAST_DEC,	VPK_EVENT_NOTICE,	EVENT_SYS_FAST_DEC,		0x1004,	"fast decelerate")
KEY_EVENT(VPK_KEY_EVENT_SYS_FAST_TURN,	VPK_EVENT_NOTICE,	EVENT_SYS_FAST_TURN,	0x1005,	"fast turn")


KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_KEY,		VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_KEY,		0x1030,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_ACC,		VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_ACC,		0x1031,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_GSENSOR,	VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_GSENSOR,	0x1032,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_4G,			VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_4G,		0x1033,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_POWER_OFF_KEY,		VPK_EVENT_NOTICE,	EVENT_SYS_POWER_OFF_KEY,	0x1040,	"poweroff")



KEY_EVENT(VPK_KEY_EVENT_QRCODE_GEN,				VPK_EVENT_NOTICE,	EVENT_QRCODE_GEN,			0x1050,	"notice")
KEY_EVENT(VPK_KEY_EVENT_FIRMWARE_DOWNLOAD,		VPK_EVENT_NOTICE,	EVENT_FIRMWARE_DOWNLOAD,	0x1051,	"notice")




KEY_EVENT(VPK_KEY_EVENT_CAR_CRASH_WARNING,		VPK_EVENT_ALERT,	EVENT_CAR_CRASH_WARNING,	0x2001,	"alert")
KEY_EVENT(VPK_KEY_EVENT_PARKING_CRASH_WARNING,	VPK_EVENT_ALERT,	EVENT_PARKING_CRASH_WARNING, 0x2002,	"alert")

KEY_EVENT(VPK_KEY_EVENT_NO_TF_CARD,			0,				EVENT_NO_TF_CARD,		0x3001,	"exception")
KEY_EVENT(VPK_KEY_EVENT_MAX_NUM,			0,				EVENT_MAX_NUM,			0x0,	"total")
