
KEY_EVENT(VPK_KEY_EVENT_SYS_ACC_ON,		VPK_EVENT_NOTICE,	EVENT_SYS_ACC_ON,		0x1001,	"acc on")
KEY_EVENT(VPK_KEY_EVENT_SYS_ACC_OFF,	VPK_EVENT_NOTICE,	EVENT_SYS_ACC_OFF,		0x1002,	"acc off")
KEY_EVENT(VPK_KEY_EVENT_SYS_FAST_ACC,	VPK_EVENT_NOTICE,	EVENT_SYS_FAST_ACC,		0x1003,	"fast accelerate")
KEY_EVENT(VPK_KEY_EVENT_SYS_FAST_DEC,	VPK_EVENT_NOTICE,	EVENT_SYS_FAST_DEC,		0x1004,	"fast decelerate")
KEY_EVENT(VPK_KEY_EVENT_SYS_FAST_TURN,	VPK_EVENT_NOTICE,	EVENT_SYS_FAST_TURN,	0x1005,	"fast turn")

KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_KEY,		VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_KEY,		0x1030,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_ACC,		VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_ACC,		0x1031,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_GSENSOR,	VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_GSENSOR,	0x1032,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_WAKE_UP_4G,			VPK_EVENT_NOTICE,	EVENT_SYS_WAKE_UP_4G,		0x1033,	"wakeup")
KEY_EVENT(VPK_KEY_EVENT_SYS_POWER_OFF_KEY,		VPK_EVENT_NOTICE,	EVENT_SYS_POWER_OFF_KEY,	0x1040,	"poweroff")
KEY_EVENT(VPK_KEY_EVENT_SYS_POWER_OFF_ACC,		VPK_EVENT_NOTICE,	EVENT_SYS_POWER_OFF_ACC,	0x1041,	"poweroff")
KEY_EVENT(VPK_KEY_EVENT_SYS_POWER_OFF_GSENSOR,	VPK_EVENT_NOTICE,	EVENT_SYS_POWER_OFF_GSENSOR,0x1042,	"poweroff")
KEY_EVENT(VPK_KEY_EVENT_SYS_POWER_OFF_TIMA,		VPK_EVENT_NOTICE,	EVENT_SYS_POWER_OFF_TIMA,	0x1043,	"poweroff")
KEY_EVENT(VPK_KEY_EVENT_SYS_POWER_OFF_VOLTAGE_LOW,	VPK_EVENT_EXCEP,	EVENT_SYS_POWER_OFF_VOLTAGE_LOW,	0x1044,	"exception")

KEY_EVENT(VPK_KEY_EVENT_QRCODE_GEN,				VPK_EVENT_NOTICE,	EVENT_QRCODE_GEN,			0x1050,	"notice")
KEY_EVENT(VPK_KEY_EVENT_FIRMWARE_DOWNLOAD,		VPK_EVENT_NOTICE,	EVENT_FIRMWARE_DOWNLOAD,	0x1051,	"notice")
KEY_EVENT(VPK_KEY_EVENT_UPDATE_SYSTEM,			VPK_EVENT_NOTICE,	EVENT_UPDATE_SYSTEM,		0x1052,	"notice")
KEY_EVENT(VPK_KEY_EVENT_DEVICE_UNBIND,			VPK_EVENT_NOTICE,	EVENT_DEVICE_UNBIND,		0x1060,	"notice")

KEY_EVENT(VPK_KEY_EVENT_GET_CUR_VIDEO_SUCCESS,	VPK_EVENT_NOTICE,	EVENT_GET_CUR_VIDEO_SUCCESS,0x1100,	"notice")
KEY_EVENT(VPK_KEY_EVENT_GET_CUR_VIDEO_FAILED,	VPK_EVENT_NOTICE,	EVENT_GET_CUR_VIDEO_FAILED,	0x1101,	"notice")

KEY_EVENT(VPK_KEY_EVENT_CAR_CRASH_NOTICE,		VPK_EVENT_NOTICE,	EVENT_CAR_CRASH_NOTICE,		0x1201,	"notice")
KEY_EVENT(VPK_KEY_EVENT_PARKING_CRASH_NOTICE,	VPK_EVENT_NOTICE,	EVENT_PARKING_CRASH_NOTICE,	0x1202,	"notice")

KEY_EVENT(VPK_KEY_EVENT_CAR_CRASH_WARNING,		VPK_EVENT_ALERT,	EVENT_CAR_CRASH_WARNING,	0x2001,	"alert")
KEY_EVENT(VPK_KEY_EVENT_PARKING_CRASH_WARNING,	VPK_EVENT_ALERT,	EVENT_PARKING_CRASH_WARNING,0x2002,	"alert")

KEY_EVENT(VPK_KEY_EVENT_NO_TF_CARD,				VPK_EVENT_EXCEP,	EVENT_NO_TF_CARD,			0x3001,	"exception")
KEY_EVENT(VPK_KEY_EVENT_TF_CARD_WRITE_PROTECT,	VPK_EVENT_EXCEP,	EVENT_TF_CARD_WRITE_PROTECT,0x3002,	"exception")
KEY_EVENT(VPK_KEY_EVENT_TF_CARD_FULL,			VPK_EVENT_EXCEP,	EVENT_TF_CARD_FULL,			0x3003,	"exception")
KEY_EVENT(VPK_KEY_EVENT_FILE_READ_ERROR,		VPK_EVENT_EXCEP,	EVENT_FILE_READ_ERROR,		0x3004,	"exception")
KEY_EVENT(VPK_KEY_EVENT_MEMORY_ERROR,			VPK_EVENT_EXCEP,	EVENT_MEMORY_ERROR,			0x3005,	"exception")
KEY_EVENT(VPK_KEY_EVENT_TF_CARD_WR_ERROR,		VPK_EVENT_EXCEP,	EVENT_TF_CARD_WR_ERROR,		0x3006,	"exception")
KEY_EVENT(VPK_KEY_EVENT_TF_CARD_MIN_ERROR,		VPK_EVENT_EXCEP,	EVENT_TF_CARD_MIN_ERROR,	0x3007,	"exception")
KEY_EVENT(VPK_KEY_EVENT_REAR_SENSOR_REMOVE,		VPK_EVENT_EXCEP,	EVENT_REAR_SENSOR_REMOVE,	0x3008,	"exception")
KEY_EVENT(VPK_KEY_EVENT_FILE_NOT_EXIST,			VPK_EVENT_EXCEP,	EVENT_FILE_NOT_EXIST,		0x3009,	"exception")

KEY_EVENT(VPK_KEY_EVENT_VIDEOREC_FINISH,		VPK_EVENT_NOTICE,	EVENT_VIDEOREC_FINISH,		0x5001,	"notice")
KEY_EVENT(VPK_KEY_EVENT_SNAPSHOT_FINISH,		VPK_EVENT_NOTICE,	EVENT_SNAPSHOT_FINISH,		0x5002,	"notice")

// hwclock -s -u
KEY_EVENT(VPK_KEY_EVENT_UPDATE_SYS_TIME,		VPK_EVENT_NOTICE,	EVENT_UPDATE_SYS_TIME,		0x8001,	"time")
KEY_EVENT(VPK_KEY_EVENT_MAX_NUM,				0,					EVENT_MAX_NUM_FIELD,		0x0,	"total")
